package com.jaimelarin.model;
// Generated 12-nov-2014 21:33:00 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "app_db"
)
public class Cliente implements java.io.Serializable {

    private Integer idCliente;
    private Estado estado;
    private Pais pais;
    private Region region;
    private String codCliente;
    private String nombres;
    private String apellidos;
    private Date fechaNac;
    private String domicilio;

    public Cliente() {
    }

    public Cliente(Estado estado, Pais pais, Region region, String codCliente, String nombres, String apellidos, Date fechaNac, String domicilio) {
        this.estado = estado;
        this.pais = pais;
        this.region = region;
        this.codCliente = codCliente;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.fechaNac = fechaNac;
        this.domicilio = domicilio;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_cliente", unique = true, nullable = false)
    public Integer getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_estado", nullable = false)
    public Estado getEstado() {
        return this.estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_pais", nullable = false)
    public Pais getPais() {
        return this.pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_region", nullable = false)
    public Region getRegion() {
        return this.region;
    }

    public void setRegion(Region region) {
        this.region = region;
    }

    @Column(name = "cod_cliente", nullable = false, length = 10)
    public String getCodCliente() {
        return this.codCliente;
    }

    public void setCodCliente(String codCliente) {
        this.codCliente = codCliente;
    }

    @Column(name = "nombres", nullable = false, length = 45)
    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    @Column(name = "apellidos", nullable = false, length = 45)
    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_nac", nullable = false, length = 19)
    public Date getFechaNac() {
        return this.fechaNac;
    }

    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }

    @Column(name = "domicilio", nullable = false)
    public String getDomicilio() {
        return this.domicilio;
    }

    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    @Override
    public String toString() {
        return "Cliente{" + "idCliente=" + idCliente + ", estado=" + estado + ", pais=" + pais + ", region=" + region + ", codCliente=" + codCliente + ", nombres=" + nombres + ", apellidos=" + apellidos + ", fechaNac=" + fechaNac + ", domicilio=" + domicilio + '}';
    }

}
