package com.jaimelarin.model;
// Generated 12-nov-2014 21:33:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "app_db"
)
public class Pais implements java.io.Serializable {

    private Integer idPais;
    private Region region;
    private String codPais;
    private String pais;
    private Set clientes = new HashSet(0);
    private Set estados = new HashSet(0);

    public Pais() {
    }

    public Pais(Region region, String codPais, String pais) {
        this.region = region;
        this.codPais = codPais;
        this.pais = pais;
    }

    public Pais(Region region, String codPais, String pais, Set clientes, Set estados) {
        this.region = region;
        this.codPais = codPais;
        this.pais = pais;
        this.clientes = clientes;
        this.estados = estados;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_pais", unique = true, nullable = false)
    public Integer getIdPais() {
        return this.idPais;
    }

    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_region", nullable = false)
    public Region getRegion() {
        return this.region;
    }

    public void setRegion(Region region) {
        this.region = region;
    }

    @Column(name = "cod_pais", nullable = false, length = 10)
    public String getCodPais() {
        return this.codPais;
    }

    public void setCodPais(String codPais) {
        this.codPais = codPais;
    }

    @Column(name = "pais", nullable = false, length = 45)
    public String getPais() {
        return this.pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    @OneToMany(fetch = FetchType.EAGER, targetEntity = Pais.class, mappedBy = "clientes")
    public Set getClientes() {
        return this.clientes;
    }

    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

    @OneToMany(fetch = FetchType.EAGER, targetEntity = Pais.class, mappedBy = "estados")
    public Set getEstados() {
        return this.estados;
    }

    public void setEstados(Set estados) {
        this.estados = estados;
    }

    @Override
    public String toString() {
        return "Pais{" + "idPais=" + idPais + ", region=" + region + ", codPais=" + codPais + ", pais=" + pais + ", clientes=" + clientes + ", estados=" + estados + '}';
    }

}
