package com.jaimelarin.model;
// Generated 12-nov-2014 21:33:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "app_db"
)
public class Region implements java.io.Serializable {

    private Integer idRegion;
    private String codRegion;
    private String region;
    private Set clientes = new HashSet(0);
    private Set paises = new HashSet(0);

    public Region() {
    }

    public Region(String codRegion, String region) {
        this.codRegion = codRegion;
        this.region = region;
    }

    public Region(String codRegion, String region, Set clientes, Set paises) {
        this.codRegion = codRegion;
        this.region = region;
        this.clientes = clientes;
        this.paises = paises;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_region", unique = true, nullable = false)
    public Integer getIdRegion() {
        return this.idRegion;
    }

    public void setIdRegion(Integer idRegion) {
        this.idRegion = idRegion;
    }

    @Column(name = "cod_region", nullable = false, length = 10)
    public String getCodRegion() {
        return this.codRegion;
    }

    public void setCodRegion(String codRegion) {
        this.codRegion = codRegion;
    }

    @Column(name = "region", nullable = false, length = 45)
    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    @OneToMany(fetch = FetchType.EAGER, targetEntity = Region.class, mappedBy = "clientes")
    public Set getClientes() {
        return this.clientes;
    }

    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

    @OneToMany(fetch = FetchType.EAGER, targetEntity = Region.class, mappedBy = "paises")
    public Set getPaises() {
        return this.paises;
    }

    public void setPaises(Set paises) {
        this.paises = paises;
    }

    @Override
    public String toString() {
        return "Region{" + "idRegion=" + idRegion + ", codRegion=" + codRegion + ", region=" + region + ", clientes=" + clientes + ", paises=" + paises + '}';
    }

}
